---
ID: "54cf2348-c412-42f8-9045-4f425b4a1633"
Parent: "2d4177d1-2658-498e-ab07-1f98208f966b"
Template: "2d4177d1-2658-498e-ab07-1f98208f966b"
Path: /sitecore/templates/Project/BMW/Pages/Archive Products Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{75E16E2E-B921-4504-A08A-E102B9D5CCE1}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211030T082816Z
