---
ID: "d5620faa-58da-4a2c-960c-25a1d5c17f32"
Parent: "54556e02-e0ff-40e5-bbe0-050beb747e6e"
Template: "54556e02-e0ff-40e5-bbe0-050beb747e6e"
Path: /sitecore/templates/Project/BMW/Pages/Authentication/Logging Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{329BA033-2681-45A2-A117-67D5F25E3013}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211112T183032Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
