---
ID: "3a874419-83e0-4985-961b-78305a05421d"
Parent: "24389a55-e06a-415a-93c4-26cb6a36b7a2"
Template: "24389a55-e06a-415a-93c4-26cb6a36b7a2"
Path: /sitecore/templates/Project/BMW/Pages/German Products Page/__Standard Values
DB: master
SharedFields:
- ID: "f1a1fe9e-a60c-4ddb-a3a0-bb5b29fe732e"
  Hint: __Renderings
  Type: layout
  Value: |
    <r xmlns:xsd="http://www.w3.org/2001/XMLSchema">
      <d
        id="{FE5D7FDF-89C0-4D99-9AA3-B5FBD009C9F3}"
        l="{32243639-40B2-48C7-B250-60646C6BEBC3}" />
    </r>
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211030T082816Z
